function ddth = Angular_Accelaration(g,l,th)
%ANGULAR_ACCELARATION
%    DDTH = ANGULAR_ACCELARATION(G,L,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Oct-2020 19:32:01

ddth = -(g.*sin(th))./l;
