function equ_F = predict_fj(m,g,l,dt,th,dth,ddth)
%PREDICT_FJ
%    EQU_F = PREDICT_FJ(M,G,L,DT,TH,DTH,DDTH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Oct-2020 19:32:02

equ_F = reshape([1.0,0.0,-(g.*cos(th))./l,dt,1.0,0.0,0.0,dt,0.0],[3,3]);
