function equ_f = predict_f(m,g,l,dt,th,dth,ddth)
%PREDICT_F
%    EQU_F = PREDICT_F(M,G,L,DT,TH,DTH,DDTH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Oct-2020 19:32:01

equ_f = [th+dt.*dth;dth+ddth.*dt;-(g.*sin(th))./l];
