function ddth = Angular_Accelaration(omega_n,th)
%ANGULAR_ACCELARATION
%    DDTH = ANGULAR_ACCELARATION(OMEGA_N,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 00:15:33

ddth = -omega_n.^2.*sin(th);
