function equ_h = predict_h(m,g,l,dt,th,dth,ddth)
%PREDICT_H
%    EQU_H = PREDICT_H(M,G,L,DT,TH,DTH,DDTH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 00:15:33

equ_h = [th;dth;ddth];
