function equ_f = predict_f(m,g,l,dt,th,dth,ddth)
%PREDICT_F
%    EQU_F = PREDICT_F(M,G,L,DT,TH,DTH,DDTH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 00:15:33

equ_f = [th+dt.*dth+dt.^2./2.0;dth+ddth.*dt;-(g.*sin(th))./l];
