%% Pre-processor Stage 1
% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/jameshansen/Documents/2020/EEE4022S/Justin Sims/Overall File Log2.xlsx
%    Worksheet: 11_34_16
%
% Auto-generated by MATLAB on 22-Oct-2020 12:57:17

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "11_34_16";
opts.DataRange = "H2:H35050";

% Specify column names and types
opts.VariableNames = "VarName8";
opts.VariableTypes = "double";

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, "VarName8", "TreatAsMissing", '');

% Import the data
tbl = readtable("/Users/jameshansen/Documents/2020/EEE4022S/Justin Sims/Overall File Log2.xlsx", opts, "UseExcel", false);
%% Convert to output type
VarName8 = tbl.VarName8;
writematrix(VarName8,'raw_data','FileType','text')

%% Clear temporary variables
clear opts tbl